### ISSUE TITLE
Text rendering looks bad at small font sizes 

### ISSUE THREAD

**Issue by uniquejack** [bholcomb/glWebKit#2]
I've been playing around with EAWebkit and I can't manage to make the font look nice at small font sizes (font-size: 12px;). Here's an example:

![image](https://user-images.githubusercontent.com/6839120/49703656-ef073e00-fc07-11e8-8ee0-4c695c6ee0c1.png)

I've tried to compile EAWebkit by myself from ychin mirror to make sure that EAText was usingFreetype, but I had the same result: not only I'm having strange issues with latin characters but also the font looks pretty bad as you can see, why?

**Comment by uniquejack** [comment]
Yeah sure,
here some comparisions:
BeamNG EAWebkit Demo:

![beamng_eawebkit](https://user-images.githubusercontent.com/6839120/50447110-494b1300-0919-11e9-915b-dd95cfe4d905.JPG)

Google Chrome:
![chrome](https://user-images.githubusercontent.com/6839120/50447118-549e3e80-0919-11e9-958e-3491a43bbb4d.JPG)

glWebkit:
![glwebkit](https://user-images.githubusercontent.com/6839120/50447121-5bc54c80-0919-11e9-8b5b-09183b275d6a.JPG)

html files:
[sampleCode.zip](https://github.com/bholcomb/glWebKit/files/2710303/sampleCode.zip)

**Comment by bholcomb** [comment]
You seem to be getting different fonts between glWebkit, beamNG webkit and chrome.  On glWebkit, it looks like you're getting times new roman since thats the only font that the example loads by default.  You'll either need to manually load other fonts, or use CSS @font-face to load the fonts for your webpage. 

`<style>
@font-face {
  font-family: 'Roboto';
  src: url('Roboto-Regular.ttf') format('truetype');
}
  
* {
  font-family: Roboto;
}
</style>
`

Let me know if that helps.  

Cheers, 

Bob
